-- Update OWASP Dependency-Track with properly formatted content matching the original site

UPDATE projects SET
  tabs = '[
    {
      "id": "main",
      "name": "Main",
      "content": "For more details about Dependency-Track see the projects website at https://dependencytrack.org\n\nDependency-Track is an intelligent Component Analysis platform that allows organizations to identify and reduce risk in the software supply chain. Dependency-Track takes a unique and highly beneficial approach by leveraging the capabilities of Software Bill of Materials (SBOM). This approach provides capabilities that traditional Software Composition Analysis (SCA) solutions cannot achieve.\n\n[YOUTUBE]https://www.youtube.com/watch?v=208W-pUOEU8[/YOUTUBE]\n\nAt a high-level, Dependency-Track takes inventory of all third-party and open source components, continuously monitors them for known security and license risks, and provides organizations the ability to quickly respond to new threats. Dependency-Track monitors component usage across all versions of every application in its portfolio in order to proactively identify risk across an enterprise.",
      "order": 1
    },
    {
      "id": "features", 
      "name": "Features",
      "content": "- Consumes and produces CycloneDX Software Bill of Materials (SBOM)\n- Consumes and produces CycloneDX Vulnerability Exploitability Exchange (VEX)\n- **Full-stack component support for:**\n  - Applications\n  - Libraries\n  - Frameworks\n  - Operating systems\n  - Containers\n  - Firmware\n  - Files\n  - Hardware\n  - Services\n- Tracks component usage across every application in an organizations portfolio\n- Quickly identify what is affected, and where\n- **Identifies multiple forms of risk including:**\n  - Components with known vulnerabilities\n  - Out-of-date components\n  - Modified components\n  - License risk\n  - More coming soon…\n- **Integrates with multiple sources of vulnerability intelligence including:**\n  - National Vulnerability Database (NVD)\n  - GitHub Advisories\n  - Sonatype OSS Index\n  - VulnDB from Risk Based Security\n  - More coming soon.\n- Helps to prioritize mitigation by incorporating support for the Exploit Prediction Scoring System (EPSS)\n- Maintain a private vulnerability database of vulnerability components\n- **Robust policy engine with support for global and per-project policies:**\n  - Security risk and compliance\n  - License risk and compliance\n  - Operational risk and compliance\n- **Ecosystem agnostic with built-in repository support for:**\n  - Cargo (Rust)\n  - Composer (PHP)\n  - Gems (Ruby)\n  - Hex (Erlang/Elixir)\n  - Maven (Java)\n  - NPM (Javascript)\n  - NuGet (.NET)\n  - Pypi (Python)\n  - More coming soon.\n- **Identifies APIs and external service components including:**\n  - Service provider\n  - Endpoint URIs\n  - Data classification\n  - Directional flow of data\n  - Trust boundary traversal\n  - Authentication requirements\n- Includes a comprehensive auditing workflow for triaging results\n- Configurable notifications supporting Slack, Microsoft Teams, WebEx, Webhooks, and Email\n- Supports standardized SPDX license IDs and tracks license use by component\n- Easy to read metrics for components, projects, and portfolio\n- Native support for Kenna Security, Fortify SSC, ThreadFix, and DefectDojo\n- API-first design facilitates easy integration with other systems\n- API documentation available in OpenAPI format\n- OAuth 2.0 + OpenID Connect (OIDC) support for single sign-on (authN/authZ)\n- Supports internally managed users, Active Directory/LDAP, and API Keys\n- Simple to install and configure. Get up and running in just a few minutes",
      "order": 2
    },
    {
      "id": "integrations",
      "name": "Integrations", 
      "content": "## CI/CD Integration\n\nDependency-Track provides extensive integration capabilities for modern software development workflows:\n\n### Build Tool Integration\n- **Maven Plugin**: https://github.com/DependencyTrack/dependency-track-maven-plugin\n- **Gradle Plugin**: Native CycloneDX Gradle plugin support\n- **NPM Integration**: JavaScript/Node.js ecosystem support\n- **Python Integration**: pip and poetry support\n- **Docker Integration**: Container image scanning capabilities\n\n### CI/CD Platform Support\n- **Jenkins**: Official Jenkins plugin available\n- **GitHub Actions**: Community-maintained actions\n- **GitLab CI**: Pipeline integration examples\n- **Azure DevOps**: Extension available in marketplace\n- **TeamCity**: Plugin support\n\n### Security Platform Integration\n- **Fortify SSC**: Software Security Center integration\n- **ThreadFix**: Vulnerability management platform\n- **DefectDojo**: Application security management\n- **Kenna Security**: Risk-based vulnerability management\n\n### Notification Systems\n- **Slack**: Real-time notifications and alerts\n- **Microsoft Teams**: Team collaboration integration\n- **WebEx**: Enterprise messaging support\n- **Email**: SMTP-based notifications\n- **Webhooks**: Custom integrations via HTTP callbacks\n\n### Enterprise Systems\n- **LDAP/Active Directory**: Enterprise authentication\n- **SSO Solutions**: SAML and OpenID Connect support\n- **JIRA**: Issue tracking integration\n- **ServiceNow**: IT service management integration",
      "order": 3
    },
    {
      "id": "installation",
      "name": "Installation",
      "content": "Dependency-Track is distributed as Docker containers.\n\n## Docker Compose\n\n```bash\ncurl -LO https://dependencytrack.org/docker-compose.yml\ndocker-compose up -d\n```\n\n## Docker Swarm\n\n```bash\ncurl -LO https://dependencytrack.org/docker-compose.yml\ndocker swarm init\ndocker stack deploy -c docker-compose.yml dtrack\n```\n\n## Additional Installation Options\n\n### System Requirements\n- **Memory**: 4GB RAM minimum (8GB+ recommended)\n- **Storage**: 20GB available disk space\n- **Java**: OpenJDK 11 or higher\n- **Database**: PostgreSQL 10+ (included in Docker setup)\n\n### Network Requirements\n- **Outbound HTTPS**: Access to vulnerability data sources\n- **Port 8080**: Web interface (configurable)\n- **Port 8081**: API endpoint (configurable)\n\n### Configuration\nAfter installation:\n1. **Initial Setup**: Change default admin password (admin/admin)\n2. **Data Sources**: Configure vulnerability intelligence feeds\n3. **Teams & Permissions**: Set up user access controls\n4. **Notifications**: Configure alert channels\n5. **Integrations**: Connect CI/CD tools and scanners",
      "order": 4
    },
    {
      "id": "news",
      "name": "News",
      "content": "- 2022/05/18 v4.5.0 Released\n- 2022/02/18 v4.4.1 Released\n- 2022/02/17 v4.4.0 Released\n- 2021/09/20 v4.3.6 Released\n- 2021/09/20 v4.3.5 Released\n- 2021/08/31 v4.3.4 Released\n- 2021/08/20 v4.3.3 Released\n- 2021/08/07 v4.3.2 Released\n- 2021/08/03 v4.3.1 Released\n- 2021/08/02 v4.3.0 Released\n- 2021/05/07 v4.2.2 Released\n- 2021/03/20 v4.2.1 Released\n- 2021/03/17 v4.2.0 Released\n- 2021/02/09 v4.1.0 Released\n- 2021/01/12 v4.0.1 Released\n- 2021/01/03 v4.0.0 Released\n- 2020/03/22 v3.8.0 Released\n- 2020/01/07 v3.7.1 Released\n- 2019/12/16 v3.7.0 Released\n- 2019/10/01 v3.6.1 Released\n- 2019/09/28 v3.6.0 Released\n- 2019/07/17 v3.5.1 Released\n- 2019/06/07 v3.5.0 Released\n- 2019/04/16 v3.4.1 Released\n- 2018/12/22 v3.4.0 Released\n- 2018/11/13 v3.3.1 Released\n- 2018/10/25 v3.3.0 Released\n- 2018/10/02 v3.2.2 Released\n- 2018/09/21 v3.2.1 Released\n- 2018/09/06 v3.2.0 Released\n- 2018/06/19 v3.1.0 Released\n- 2018/05/02 v3.0.4 Released\n- 2018/04/13 v3.0.3 Released\n- 2018/03/30 v3.0.2 Released\n- 2018/03/29 v3.0.1 Released\n- 2018/03/27 v3.0.0 Released\n- 2017/10/08 v3.0 Updates to community\n- 2017/06/16 Presentation at OWASP Summit 2017",
      "order": 5
    },
    {
      "id": "our-supporters",
      "name": "Our Supporters", 
      "content": "Dependency-Track is developed by a worldwide team of volunteers.\n\nBut we have also been helped by many organizations, either financially or by encouraging their employees to work on Dependency-Track:\n\n- **Risk Based Security**\n- **KPMG**\n\n## Project Leadership\n\n### Project Leaders\n- **Steve Springett**: Project Leader and Creator\n- **Niklas Düster**: Core Contributor and Maintainer\n\n### How to Support\n- Contribute code and documentation\n- Report issues and feature requests\n- Share usage experiences\n- Provide funding for development\n- Sponsor infrastructure and resources\n\nFor more information about supporting the OWASP Dependency-Track project, please contact the project leaders or the OWASP Foundation.",
      "order": 6
    },
    {
      "id": "executive-order-14028",
      "name": "Executive Order 14028",
      "content": "## U.S. Executive Order 14028\n\nSince its inception in 2013, OWASP Dependency-Track has been at the forefront of analyzing bill of materials for cybersecurity risk identification and reduction. Dependency-Track allows organizations and governments to operationalize SBOM in conformance with U.S. Executive Order 14028.\n\n- Supports the OWASP CycloneDX BOM format specifically defined in the NTIA Minimum Elements For a Software Bill of Materials(SBOM)\n- Consumes and analyzes SBOMs for known security, operational, and license risk\n- Ideal for use in procurement and continuous integration and delivery environments\n- Supports the OWASP CycloneDX VEX format exceeding the Vulnerability Exploitability Exchange requirements defined by CISA\n\n## For software consumers\n\n- Tracks all systems and applications that have SBOMs\n- Upload SBOMs through the user interface or via automation\n- Components defined in SBOMs will be analyzed for known vulnerabilities using multiple sources of vulnerability intelligence, including the NVD\n- Displays all identified vulnerabilities and vulnerable components for every SBOM analyzed\n- Upload CycloneDX VEX obtained from suppliers to gain insight into the vulnerable components that pose risk, and the ones that don''t\n- Quickly identify all systems and applications that have a specific component or are affected by a specific vulnerability\n- Helps to prioritize mitigation by incorporating support for the Exploit Prediction Scoring System (EPSS)\n- Evaluate the portfolio of systems and applications against user-configurable security, operational, and license policies\n\n## For software producers\n\n- Create and consume CycloneDX SBOMs in development pipelines\n- SBOMs will be analyzed for known security, operational, and license risk\n- Evaluates the portfolio of applications against user-configurable security, operational, and license policies\n- Inspect security findings and make audit decisions about the relevance and exploitability of each vulnerability\n- CycloneDX BOMs can be dynamically generated from current inventory for any application\n- CycloneDX VEX is dynamically generated from audit decisions for each application\n- An API-first design allows software producers to extract SBOMs for released products, produce VEX whenever updated audit decisions are made, and make data available to internal systems responsible for SBOM and VEX distribution.\n\n## Other considerations\n\n- Both CycloneDX and Dependency-Track are full-stack solutions supporting software, hardware, and services. The CycloneDX standard and use with Dependency-Track is not limited to SBOM use cases.\n- Software consumers may optionally audit security findings from vendor SBOMs. If consumers discover discrepancies in vendor supplied VEX, consumers can share their own auto-generated VEX with suppliers, completing a bi-directional exchange of vulnerability and exploitability information.",
      "order": 7
    }
  ]'::jsonb,
  
  content_last_updated = NOW()

WHERE slug = 'dependency-track';
